=== PatternBuilder/pattern-kit/resources/library/components/promo/api/promo.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Promo",
    "description": "",
    "category": "component",
    "type": "object",
    "format": "grid",
    "properties": {
        "headline": {
            "title": "Headline",
            "type": "string"
        },
        "text": {
            "title": "Text",
            "type": "string",
            "format": "textarea"
        },
        "cta": {
            "$ref": "link.json"
        },
        "name": {
            "type": "string",
            "enum": [ "promo" ],
            "options": {
                "hidden": true
            }
        }
    },
    "required": [ "headline", "text", "cta" ],
    "additionalProperties": false
}

=== PatternBuilder/pattern-kit/resources/library/components/promo/tests/promo.tests.json
{
    "headline": "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    "text": "Aut, distinctio esse voluptates? Nobis molestiae ducimus sequi illum laudantium reiciendis architecto tempore sapiente perferendis dolore nisi odit et, nostrum alias recusandae?",
    "cta": {
        "href": "http://redhat.com",
        "text": "Learn More",
        "title": "Click me!"
    },
    "name": "promo"
}
