=== PatternBuilder/pattern-kit/resources/library/components/pagination/api/pagination.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Pagination",
    "category": "component",
    "type": "object",
    "format": "grid",
    "required": [ "name", "pages" ],
    "additionalProperties": false,
    "properties": {
        "name": {
            "type": "string",
            "enum": [ "pagination" ],
            "options": {
                "hidden": true
            }
        },
        "template": {
            "type": "string",
            "options": {
                "hidden": true
            }
        },
        "misc_data": {
            "type": "string",
            "options": {
                "hidden": true
            }
        },
        "config": {
            "type": "object",
            "properties": {
                "align": {
                    "title": "Alignment",
                    "type": "string",
                    "default": "center",
                    "enum": [ "left", "right", "center" ]
                }
            }
        },
        "pages": {
            "format": "table",
            "description": "Individual page links",
            "type": "array",
            "minItems": 1,
            "items": {
                "type": "object",
                "format": "grid",
                "required": [ "state", "link" ],
                "properties": {
                    "state": {
                        "type": "string",
                        "enum": [ "active", "inactive" ]
                    },
                    "link": {
                        "$ref": "link.json"
                    }
                }
            }
        },
        "buttons": {
            "type": "object",
            "properties": {
                "prev": {
                    "description": "Previous Button",
                    "type": "object",
                    "format": "grid",
                    "required": [ "state", "link" ],
                    "properties": {
                        "state": {
                            "type": "string",
                            "enum": [ "active", "inactive" ]
                        },
                        "link": {
                            "$ref": "link.json"
                        }
                    }
                },
                "next": {
                    "description": "Next Button",
                    "type": "object",
                    "format": "grid",
                    "required": [ "state", "link" ],
                    "properties": {
                        "state": {
                            "type": "string",
                            "enum": [ "active", "inactive" ]
                        },
                        "link": {
                            "$ref": "link.json"
                        }
                    }
                }
            }
        }
    }
}

=== PatternBuilder/pattern-kit/resources/library/components/pagination/tests/pagination.tests.json
{
    "name": "pagination",
    "config": {
        "align": "center"
    },
    "buttons": {
        "prev": {
            "state": "inactive",
            "link": {
                "href": "#",
                "text": "Previous"
            }
        },
        "next": {
            "state": "active",
            "link": {
                "href": "#",
                "text": "Next"
            }
        }
    },
    "pages": [
        {
            "state": "inactive",
            "link": {
                "text": "1"
            }
        },
        {
            "state": "active",
            "link": {
                "text": "2",
                "href": "#",
                "title": "page 2"
            }
        },
        {
            "state": "active",
            "link": {
                "text": "3",
                "href": "#",
                "title": "page 3"
            }
        },
        {
            "state": "active",
            "link": {
                "text": "4",
                "href": "#",
                "title": "page 4"
            }
        },
        {
            "state": "active",
            "link": {
                "text": "5",
                "href": "#",
                "title": "page 5"
            }
        }
    ]
}
