=== PatternBuilder/pattern-kit/resources/library/components/quote/api/quote.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Quote",
    "category": "component",
    "type": "object",
    "format": "grid",
    "properties": {
        "name": {
            "type": "string",
            "readonly": "true",
            "default": "quote",
            "options": {
                "hidden": true
            }
        },
        "template": {
            "type": "string",
            "options": {
                "hidden": true
            }
        },
        "misc_data": {
            "type": "string",
            "options": {
                "hidden": true
            }
        },
        "quotation": {
            "title": "Quote Text",
            "type": "string",
            "format": "textarea"
        },
        "attribution_name": {
            "title": "Attribution",
            "description": "Who said it?",
            "type": "string"
        },
        "attribution_title": {
            "title": "Attribution Title",
            "description": "What is their job title?",
            "type": "string"
        }
    },
    "required": [ "name", "quotation", "attribution_name" ],
    "additionalProperties": false
}

=== PatternBuilder/pattern-kit/resources/library/components/quote/tests/quote.tests.json
{
    "name": "quote",
    "quotation": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio explicabo natus officiis corporis neque laudantium quae animi minima mollitia inventore exercitationem, illum architecto voluptatibus voluptas cum, nemo incidunt vel laborum.",
    "attribution_name": "John Smith",
    "attribution_title": "President"
}
