=== PatternBuilder/pattern-kit/resources/library/patterns/featured_event/api/featured_event.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Featured event",
    "category": "pattern",
    "type": "object",
    "additionalProperties": false,
    "required": [ "background_color", "title", "events" ],
    "properties": {
        "name": {
            "type": "string",
            "enum": [ "featured_event" ],
            "options": {
                "hidden": true
            }
        },
        "meta": {
            "type": "object",
            "properties": {
                "class": {
                    "options": {
                        "hidden": true
                    },
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string",
                    "options": {
                        "hidden": true
                    }
                },
                "uniqueId": {
                    "type": "string",
                    "options": {
                        "hidden": true
                    }
                }
            }
        },
        "background_color": {
            "title": "Band Background",
            "type": "string",
            "enum": [ "gray", "white" ]
        },
        "title": {
            "title": "Band Title",
            "type": "string",
            "options": {
                "preview": true
            }
        },
        "headline": {
            "title": "Band Headline",
            "type": "string",
            "options": {
                "preview": true
            }
        },
        "events": {
            "title": "Events",
            "type": "array",
            "description": "Create one or two events",
            "items": {
                "title": "Event",
                "type": "object",
                "properties": {
                    "title": {
                        "title": "Event Title",
                        "type": "string"
                    },
                    "date": {
                        "title": "Event Date",
                        "type": "string"
                    },
                    "category": {
                        "title": "Event Category",
                        "type": "string"
                    },
                    "summary": {
                        "title": "Event Summary",
                        "type": "string",
                        "format": "textarea"
                    },
                    "image": {
                        "title": "Event Image or Logo",
                        "$ref": "image.json"
                    },
                    "link": {
                        "title": "Event Link",
                        "$ref": "link.json"
                    }
                }
            }
        }
    }
}

=== PatternBuilder/pattern-kit/resources/library/patterns/featured_event/tests/featured_event.tests.json
{
    "name": "featured_event",
    "background_color": "gray",
    "title": "Featured Events",
    "headline": "",
    "meta": {
        "uniqueId": "1234"
    },
    "events": [
        {
            "title": "Open Source Day Celebration",
            "date": "July 11, 2015",
            "category": "Rollerskating party",
            "image": {
                "src": "/fixtures/images/red.png",
                "alt": ""
            },
            "summary": "In lobortis, justo euismod consequat dignissim, lorem dolor mollis ligula, a congue diam nisi eu tortor. Phasellus efficitur turpis eget massa pulvinar pellentesque. Vestibulum at dui ac diam auctor commodo placerat vitae tellus.",
            "link": {
                "href": "http://www.redhat.com",
                "title": "",
                "text": "Register now"
            }
        },
        {
            "title": "Red Hat Sponsored Event",
            "date": "August 27, 2015",
            "category": "Summit",
            "image": {
                "src": "/fixtures/images/blue.png",
                "alt": ""
            },
            "summary": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas semper lacus sed dolor imperdiet, quis finibus est gravida. Maecenas fermentum, ante ut interdum interdum, sapien lectus feugiat est, condimentum feugiat arcu odio eu sem. Morbi iaculis pretium luctus. Nunc finibus sollicitudin arcu sed sodales. Nullam ut gravida erat. Duis ultrices rutrum urna. Nullam eget metus lacus. In aliquet arcu non faucibus rhoncus.",
            "link": {
                "href": "http://www.redhat.com",
                "title": "",
                "text": "Learn More"
            }
        }
    ]
}
