=== PatternBuilder/pattern-kit/resources/library/components/link_tile/api/link_tile.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Link tile",
    "description": "The link tile component can have an icon, title, headline or summary that is wrapped in a link.",
    "category": "component",
    "type": "object",
    "format": "grid",
    "properties": {
        "name": {
            "type": "string",
            "enum": [ "link_tile" ],
            "options": {
                "hidden": true
            }
        },
        "template": {
            "type": "string",
            "options": {
                "hidden": true
            }
        },
        "misc_data": {
            "type": "string",
            "options": {
                "hidden": true
            }
        },
        "config": {
            "type": "object",
            "properties": {
                "content_align": {
                    "title": "Alignment of Content",
                    "type": "string",
                    "default": "left",
                    "enum": [ "left", "right", "center" ]
                },
                "tile_height": {
                    "title": "Tile Height",
                    "type": "string",
                    "enum": [ "tall" ]
                }
            }
        },
        "title": {
            "title": "Title",
            "type": "string"
        },
        "headline": {
            "title": "Headline",
            "type": "string"
        },
        "summary": {
            "title": "Summary",
            "type": "string",
            "format": "textarea"
        },
        "link": {
            "entity": "link",
            "type": "object",
            "format": "grid",
            "properties": {
                "href": {
                    "$ref": "link.json#/properties/href"
                },
                "title": {
                    "$ref": "link.json#/properties/title"
                }
            },
            "required": [ "href" ]
        },
        "icon": {
            "title": "Icon",
            "description": "Use icon class name",
            "type": "string"
        }
    },
    "required": [ "link", "name" ],
    "additionalProperties": false
}

=== PatternBuilder/pattern-kit/resources/library/components/link_tile/tests/link_tile.tests.json
{
    "name": "link_tile",
    "config": {
        "content_align": "left",
        "tile_height": "tall"
    },
    "icon": "rh-icon-atom ",
    "title": "A link tile",
    "headline": "A link tile headline",
    "summary": "A short summary that leads to a larger story.",
    "link": {
        "href": "#",
        "title": "Link Tile Title"
    }
}
