=== PatternBuilder/pattern-kit/resources/library/components/customer_success/api/customer_success.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Customer success",
    "description": "Customer success teaser",
    "category": "component",
    "type": "object",
    "format": "grid",
    "properties": {
        "name": {
            "type": "string",
            "enum": [ "customer_success" ],
            "options": {
                "hidden": true
            }
        },
        "template": {
            "type": "string",
            "options": {
                "hidden": true
            }
        },
        "misc_data": {
            "type": "string",
            "options": {
                "hidden": true
            }
        },
        "logo": {
            "title": "Logo",
            "$ref": "image.json"
        },
        "image": {
            "title": "Photo",
            "$ref": "image.json"
        },
        "title": {
            "title": "Headline",
            "type": "string"
        },
        "summary": {
            "title": "Summary",
            "type": "string",
            "format": "textarea"
        },
        "link": {
            "$ref": "link.json"
        }
    },
    "required": [ "title", "summary", "link", "logo", "image", "name" ],
    "additionalProperties": false
}

=== PatternBuilder/pattern-kit/resources/library/components/customer_success/tests/customer_success.tests.json
{
    "name": "customer_success",
    "title": "Adobe attracts enterprise customers with cloud-based products",
    "summary": "Adobe wanted to employ an open hybrid cloud model flexible enough to operate both on premise and in the cloud. The partnership with Red Hat and Amazon Web Services has given Adobe dozens of enterprise customers using its cloud-based products and services.",
    "link": {
        "href": "#",
        "text": "Click Me"
    },
    "logo": {
        "src": "http://www.redhat.com/cms/public/Adobe_Logo_RGB_225x158_0.png"
    },
    "image": {
        "src": "http://www.redhat.com/cms/public/card_adobe_systems_mitch_nelson_370x190.jpg"
    }
}
