=== PatternBuilder/pattern-kit/resources/library/components/featured_item/api/featured_item.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Featured item",
    "description": "Promoted or emphasized item",
    "category": "component",
    "type": "object",
    "format": "grid",
    "properties": {
        "name": {
            "type": "string",
            "enum": [ "featured_item" ],
            "options": {
                "hidden": true
            }
        },
        "template": {
            "type": "string",
            "options": {
                "hidden": true
            }
        },
        "misc_data": {
            "type": "string",
            "options": {
                "hidden": true
            }
        },
        "title": {
            "title": "Title",
            "type": "string"
        },
        "type": {
            "title": "Category or Type",
            "type": "string"
        },
        "date": {
            "title": "Date",
            "type": "string"
        },
        "location": {
            "title": "Location",
            "type": "string"
        },
        "logo": {
            "title": "Image or Logo",
            "$ref": "image.json"
        },
        "summary": {
            "title": "Summary",
            "description": "Summary text. Anchor tags allowed",
            "type": "string",
            "format": "textarea"
        },
        "primary_link": {
            "title": "Primary Link",
            "$ref": "link.json"
        },
        "secondary_link": {
            "title": "Secondary Link",
            "$ref": "link.json"
        }
    },
    "required": [ "name", "title", "primary_link" ],
    "additionalProperties": false
}

=== PatternBuilder/pattern-kit/resources/library/components/featured_item/tests/featured_item.tests.json
{
    "name": "featured_item",
    "title": "Simplified system management",
    "date": "September 10, 2014",
    "type": "RedHat Partner Conference",
    "location": "Chicago, IL",
    "summary": "Join the virtual event on September 10 at 11 a.m. (ET) to learn how Red Hat Satellite is shaping the next generation of systems management for the Linux datacenter.",
    "primary_link": {
        "href": "#",
        "text": "Primary CTA"
    },
    "secondary_link": {
        "href": "#",
        "text": "Secondary CTA"
    },
    "logo": {
        "src": "http://www.redhat.com/cms/public/Adobe_Logo_RGB_225x158_0.png"
    }
}
