=== PatternBuilder/pattern-kit/resources/library/layouts/band/api/band.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Band",
    "category": "layout",
    "type": "object",
    "format": "grid",
    "required": ["name"],
    "additionalProperties": false,
    "properties": {
        "name": {
            "type": "string",
            "enum": ["band"],
            "options": {
                "hidden": true
            }
        },
        "template": {
            "type": "string",
            "options": {
                "hidden": true
            }
        },
        "meta": {
            "type": "object",
            "properties": {
                "class": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string"
                },
                "uniqueId": {
                    "type": "string",
                    "options": {
                        "hidden": true
                    }
                },
                "dtm": {
                    "title": "Tracking labels",
                    "description": "Used for analytics tracking to uniquely identify a section. Enter each tracking string separately.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "config": {
            "title": "Configuration",
            "type": "object",
            "format": "grid",
            "properties": {
                "collapse": {
                    "title": "Collapse band padding",
                    "type": "string",
                    "enum": ["full_top", "full_bottom", "full", "top", "bottom", "both"]
                },
                "vertical_spacing": {
                    "title": "Band vertical layout",
                    "description": "Vertical space between header, body and footer",
                    "type": "string",
                    "default": "stacked",
                    "enum": ["stacked", "tall-stacked"]
                }
            }
        },
        "background": {
            "title": "Background Options",
            "type": "object",
            "format": "grid",
            "properties": {
                "color": {
                    "type": "string",
                    "enum": ["white", "gray", "black", "rich-black", "red", "transparent"]
                },
                "image_large": {
                    "$ref": "image.json",
                    "title": "Large Screen Background"
                },
                "image_small": {
                    "$ref": "image.json",
                    "title": "Small Screen Background"
                },
                "isFixed": {
                    "title": "Fixed Background Option",
                    "type": "boolean"
                },
                "align": {
                    "title": "Alignment for background image",
                    "type": "string",
                    "enum": ["center-center", "right-center", "left-center"],
                    "default": "center-center",
                    "options": {
                        "hidden": true
                    }
                }
            }
        },
        "header": {
            "title": "Header",
            "type": "object",
            "format": "grid",
            "properties": {
                "layout": {
                    "type": "string"
                },
                "theme": {
                    "type": "string",
                    "enum": ["light", "dark"]
                },
                "content": {
                    "type": "array",
                    "maxItems": 1,
                    "items": {
                        "title": "Header Item",
                        "oneOf": [{
                            "$ref": "band_header.json"
                        }]
                    }
                }
            }
        },
        "body": {
            "title": "Body",
            "type": "object",
            "format": "grid",
            "properties": {
                "layout": {
                    "type": "string"
                },
                "theme": {
                    "type": "string",
                    "enum": ["light", "dark"]
                },
                "content": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "title": "Body Item",
                        "oneOf": [{
                            "$ref": "band_header.json"
                        }, {
                            "$ref": "cta.json"
                        }, {
                            "$ref": "customer_success.json"
                        }, {
                            "$ref": "featured_item.json"
                        }, {
                            "$ref": "generic.json"
                        }, {
                            "$ref": "image_embed.json"
                        }, {
                            "$ref": "link_tile.json"
                        }, {
                            "$ref": "pagination.json"
                        }, {
                            "$ref": "quote.json"
                        }, {
                            "$ref": "icon_panel.json"
                        }, {
                            "$ref": "icon_embed.json"
                        }, {
                            "$ref": "video_embed.json"
                        }, {
                            "$ref": "card.json"
                        }, {
                            "$ref": "group.json"
                        }, {
                            "$ref": "raw.json"
                        }]
                    }
                }
            }
        },
        "footer": {
            "title": "Footer",
            "type": "object",
            "format": "grid",
            "properties": {
                "layout": {
                    "type": "string"
                },
                "theme": {
                    "type": "string",
                    "enum": ["light", "dark"]
                },
                "content": {
                    "type": "array",
                    "maxItems": 1,
                    "items": {
                        "title": "Footer item",
                        "oneOf": [{
                            "$ref": "cta.json"
                        },{
                            "$ref": "footnote.json"
                        }]
                    }
                }
            }
        },
        "aside": {
            "title": "Aside",
            "type": "object",
            "format": "grid",
            "properties": {
                "content": {
                    "type": "array",
                    "maxItems": 1,
                    "items": {
                        "title": "Aside Item",
                        "oneOf": [{
                            "$ref": "card.json"
                        }, {
                            "$ref": "group.json"
                        }, {
                            "$ref": "raw.json"
                        }]
                    }
                }
            }
        }
    }
}

=== PatternBuilder/pattern-kit/resources/library/layouts/band/tests/band.tests.json
{
    "name": "band",
    "meta": {
        "class": [ "foo", "bar", "baz" ],
        "id": "customID",
        "uniqueId": "1234"
    },
    "background": {
        "color": "gray"
    },
    "header": {
        "content": [
            {
                "name": "group",
                "body": {
                    "layout": "9 3",
                    "content": [
                        {
                            "name": "card",
                            "config": {
                                "theme": "dark"
                            }
                        },
                        {
                            "name": "card",
                            "config": {
                                "theme": "dark"
                            }
                        }
                    ]
                }
            }
        ]
    },
    "aside": {
        "content": [
            {
                "name": "card",
                "background": {
                    "color": "black"
                },
                "body": {
                    "content": [
                        {
                            "name": "raw",
                            "content": ""
                        }
                    ]
                }
            }
        ]
    },
    "footer": {
        "layout": "8 4",
        "content": [
            {
                "name": "group",
                "body": {
                    "layout": "4 4 of 8",
                    "content": [
                        {
                            "name": "card",
                            "config": {
                                "theme": "dark"
                            }
                        },
                        {
                            "name": "card",
                            "config": {
                                "theme": "dark"
                            }
                        }
                    ]
                }
            },
            {
                "name": "card",
                "config": {
                    "theme": "dark"
                }
            }
        ]
    },
    "body": {
        "layout": "stacked",
        "content": [
            {
                "name": "group",
                "body": {
                    "layout": "gallery6",
                    "content": [
                        {
                            "name": "card",
                            "config": {
                                "theme": "dark"
                            }
                        },
                        {
                            "name": "card",
                            "config": {
                                "theme": "dark"
                            }
                        },
                        {
                            "name": "card",
                            "config": {
                                "theme": "dark"
                            }
                        },
                        {
                            "name": "card",
                            "config": {
                                "theme": "dark"
                            }
                        },
                        {
                            "name": "card",
                            "config": {
                                "theme": "dark"
                            }
                        },
                        {
                            "name": "card",
                            "config": {
                                "theme": "dark"
                            }
                        },
                        {
                            "name": "card",
                            "config": {
                                "theme": "dark"
                            }
                        },
                        {
                            "name": "card",
                            "config": {
                                "theme": "dark"
                            }
                        },
                        {
                            "name": "card",
                            "config": {
                                "theme": "dark"
                            }
                        },
                        {
                            "name": "card",
                            "config": {
                                "theme": "dark"
                            }
                        },
                        {
                            "name": "card",
                            "config": {
                                "theme": "dark"
                            }
                        },
                        {
                            "name": "card",
                            "config": {
                                "theme": "dark"
                            }
                        },
                        {
                            "name": "card",
                            "config": {
                                "theme": "dark"
                            }
                        },
                        {
                            "name": "card",
                            "config": {
                                "theme": "dark"
                            }
                        },
                        {
                            "name": "card",
                            "config": {
                                "theme": "dark"
                            }
                        },
                        {
                            "name": "card",
                            "config": {
                                "theme": "dark"
                            }
                        },
                        {
                            "name": "card",
                            "config": {
                                "theme": "dark"
                            }
                        },
                        {
                            "name": "card",
                            "config": {
                                "theme": "dark"
                            }
                        }
                    ]
                }
            }
        ]
    }
}

=== PatternBuilder/pattern-kit/resources/library/patterns/recent_videos/tests/recent_videos.tests.json
{
    "name": "band",
    "meta": {
        "uniqueId": "1234",
        "class": [ "foo", "bar", "baz" ],
        "id": "my-id"
    },
    "header": {
        "content": [
            {
                "name": "band_header",
                "headline": "This is my headline",
                "title": "Video Band"
            }
        ]
    },
    "body": {
        "layout": "4 4 4 flex",
        "content": [
            {
                "name": "card",
                "config": {
                    "theme": "dark"
                },
                "body": {
                    "content": [
                        {
                            "name": "video_embed",
                            "video": {
                                "video_src": "<iframe style=\"border: none \" srcdoc=\"<style>body{background: #c00}</style>\" ></iframe>"
                            },
                            "title": {
                                "href": "www.redhat.com",
                                "title": "Video Title",
                                "text": "Watch Video",
                                "target": "_self"
                            },
                            "summary": "JBoss solutions come in two different versions: developer community projects and enterprise products. Do you know which version to use when?"
                        }
                    ]
                }
            },
            {
                "name": "card",
                "config": {
                    "theme": "dark"
                },
                "body": {
                    "content": [
                        {
                            "name": "video_embed",
                            "video": {
                                "video_src": "<iframe style=\"border: none \" srcdoc=\"<style>body{background: #c00}</style>\" ></iframe>"
                            },
                            "title": {
                                "href": "www.redhat.com",
                                "title": "Video Title",
                                "text": "Watch Video",
                                "target": "_self"
                            },
                            "summary": "Why software-defined storage for the enterprise?"
                        }
                    ]
                }
            },
            {
                "name": "card",
                "config": {
                    "theme": "dark"
                },
                "body": {
                    "content": [
                        {
                            "name": "video_embed",
                            "video": {
                                "video_src": "<iframe style=\"border: none \" srcdoc=\"<style>body{background: #c00}</style>\" ></iframe>"
                            },
                            "title": {
                                "href": "www.redhat.com",
                                "title": "Video Title",
                                "text": "Watch Video",
                                "target": "_self"
                            },
                            "summary": "e-NABLE: Open technology, faster progress\n"
                        }
                    ]
                }
            }
        ]
    },
    "footer": {
        "content": [
            {
                "name": "cta",
                "config": {
                    "type": "primary"
                },
                "link": {
                    "href": "https://www.redhat.com/en/about/videos",
                    "title": "",
                    "text": "Explore all videos",
                    "target": "_self"
                }
            }
        ]
    }
}
