=== PatternBuilder/pattern-kit/resources/library/patterns/feature_set/api/feature_set.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Feature Set",
    "description": "",
    "category": "pattern",
    "additionalProperties": false,
    "type": "object",
    "format": "grid",
    "properties": {
        "name": {
            "type": "string",
            "enum": ["feature_set"],
            "options": {
                "hidden": true
            }
        },
        "meta": {
            "type": "object",
            "options": {
                "hidden": true
            },
            "properties": {
                "class": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string"
                },
                "uniqueId": {
                    "type": "string"
                }
            }
        },
        "config": {
            "title": "Config",
            "type": "object",
            "properties": {
                "pattern_style": {
                    "type": "string",
                    "enum": ["fset1"],
                    "options": {
                        "hidden": true
                    }
                },
                "theme": {
                    "$ref": "config.json#/properties/pattern/properties/theme"
                }
            },
            "required": ["theme"]
        },
        "background": {
            "title": "Background options",
            "type": "object",
            "format": "grid",
            "properties": {
                "image_large": {
                    "$ref": "config.json#/properties/pattern/properties/background/properties/image_large"
                },
                "image_small": {
                    "$ref": "config.json#/properties/pattern/properties/background/properties/image_small"
                },
                "color": {
                    "$ref": "config.json#/properties/pattern/properties/background/properties/color"
                }
            },
            "required": ["color"]
        },
        "header": {
            "title": "Band header",
            "type": "object",
            "properties": {
                "seo_emphasis": {
                    "$ref": "band_header.json#/properties/config/properties/seo/properties/priority",
                    "title": "SEO emphasis",
                    "description": "Emphasize element with keywords or relevant content. 'Standard' is the system default"
                },
                "title": {
                    "$ref": "band_header.json#/properties/title",
                    "options": {
                        "grid_column": 6
                    }
                },
                "headline": {
                    "$ref": "band_header.json#/properties/headline",
                    "options": {
                        "grid_column": 6
                    }
                },
                "summary": {
                    "$ref": "band_header.json#/properties/summary"
                }
            }
        },
        "features": {
            "type": "array",
            "title": "Features",
            "items": {
                "type": "object",
                "properties": {
                    "icon": {
                        "title": "Icon file name",
                        "type": "string",
                        "description": "<a target='_blank' href='http://styleguides-itmarketing.itos.redhat.com/webux/styleguide/docs/styles_-_icons.html'>Choose your icon from The RH Icon List</a>"
                    },
                    "title": {
                        "title": "Title",
                        "type": "string"
                    },
                    "summary": {
                        "title": "Summary",
                        "type": "string",
                        "format": "html",
                        "description": "Allowed tags: &lt;a&gt;&lt;br&gt;&lt;sup&gt;&lt;small&gt;"
                    },
                    "cta": {
                        "title": "Optional call-to-action button",
                        "type": "object",
                        "options": {
                            "collapsed": true
                        },
                        "properties": {
                            "link": {
                                "title": "Call-to-action",
                                "$ref": "link.json"
                            }
                        }
                    }
                }
            }
        },
        "cta": {
            "title": "Optional call-to-action button",
            "type": "object",
            "options": {
                "collapsed": true
            },
            "properties": {
                "type": {
                    "title": "CTA type",
                    "type": "string",
                    "enum": ["primary", "secondary"],
                    "default": "primary"
                },
                "link": {
                    "title": "Call-to-action",
                    "$ref": "link.json"
                }
            }
        }
    },
    "required": ["background", "features"]
}

=== PatternBuilder/pattern-kit/resources/library/patterns/feature_set/tests/feature_set.tests.json
{
    "name": "feature_set",
    "config": {
        "pattern_style": "fset1",
        "theme": "light"
    },
    "background": {
        "color": "gray",
        "image_large": {
            "src": ""
        },
        "image_small": {
            "src": ""
        },
        "isFixed": true
    },
    "header": {
        "seo_emphasis": "standard",
        "title": "Certification toolkit",
        "headline": "The information you need. All in 1 place.",
        "summary": "It shouldn't be a chore to learn about—and register for—the certification you want. We provide a number of ways to help you."
    },
    "features": [
        {
            "title": "Increase profits",
            "summary": "Maximize your team's productivity with on-demand training without the need to leave the datacenter.",
            "icon": "rh-icon-bar-graph",
            "cta": {
                "link": {
                    "href": "#",
                    "title": "Click me",
                    "text": "Click me"
                }
            }
        },
        {
            "title": "Increase productivity",
            "summary": "Maximize your team's productivity with on-demand training without the need to leave the datacenter.",
            "icon": "rh-icon-increase-productivity"
        },
        {
            "title": "Knowledgable instructors",
            "summary": "Maximize your team's productivity with on-demand training without the need to leave the datacenter.",
            "icon": "rh-icon-instructor"
        },
        {
            "title": "Solve complex issues",
            "summary": "Maximize your team's productivity with on-demand training without the need to leave the datacenter. <a href='#'>Link thing</a>",
            "icon": "rh-icon-puzzle-piece"
        }
    ],
    "cta": {
        "type": "primary",
        "link": {
            "href": "#",
            "title": "1",
            "text": "Learn more"
        }
    }
}
