=== PatternBuilder/pattern-kit/resources/library/components/video_embed/api/video_embed.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Video embed",
    "description": "The video embed component can be displayed with an inline video using a YouTube iFrame (for use in cards or as detail page) or a poster image that links to the video's detail page.",
    "category": "component",
    "type": "object",
    "format": "grid",
    "required": [ "video", "name" ],
    "additionalProperties": false,
    "properties": {
        "name": {
            "type": "string",
            "enum": [ "video_embed" ],
            "options": {
                "hidden": true
            }
        },
        "template": {
            "type": "string",
            "options": {
                "hidden": true
            }
        },
        "misc_data": {
            "type": "string",
            "options": {
                "hidden": true
            }
        },
        "video": {
            "title": "Video Source",
            "$ref": "video.json"
        },
        "title": {
            "title": "Video Title and URL",
            "$ref": "link.json"
        },
        "summary": {
            "title": "Summary of the video content",
            "type": "string",
            "format": "textarea"
        }
    }
}

=== PatternBuilder/pattern-kit/resources/library/components/video_embed/tests/video_embed.tests.json
{
    "name": "video_embed",
    "video": {
        "video_src": "<iframe style=\"border: none \" srcdoc=\"<style>body{background: #c00}</style>\" ></iframe>"
    },
    "title": "Red Hat Enterprise Linux 7: Redefining the Enterprise OS",
    "summary": "Hear from Red Hat executives how Red Hat Enterprise Linux 7 raises the bar yet again and brings the next-generation of IT to customers. Nearly 50% of business managers say they will increase their investments in collaborative development.* Choice and collaboration are where technology is headed."
}
